version: '3.7'
services:
  springapp:
    image: pnalladevops/springapp:VERSION
    ports:
    - 3030:8080
    networks:
    - mybridge
    environment:
      MONGO_DB_HOSTNAME: mongodb
      MONGO_DB_USERNAME: proddb
      MONGO_DB_PASSWORD: proddb@123
    depend_on:
     mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: proddb
      MONGO_INITDB_ROOT_PASSWORD: proddb@123
    networks:
     - mybridge

    volumes:
     - mongodbvol:/data/db


networks:
  mybridge:
   driver: bridge

volumes:
 mongodbvol:
   driver: local
